/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  CounterScriptAbi,
  CounterScriptAbiInterface,
} from "../../Counter.s.sol/CounterScriptAbi";

const _abi = [
  {
    type: "function",
    name: "IS_SCRIPT",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "run",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setUp",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
] as const;

export class CounterScriptAbi__factory {
  static readonly abi = _abi;
  static createInterface(): CounterScriptAbiInterface {
    return new utils.Interface(_abi) as CounterScriptAbiInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CounterScriptAbi {
    return new Contract(address, _abi, signerOrProvider) as CounterScriptAbi;
  }
}
