"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CounterScriptAbi__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        type: "function",
        name: "IS_SCRIPT",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "bool",
                internalType: "bool",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "run",
        inputs: [],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "setUp",
        inputs: [],
        outputs: [],
        stateMutability: "nonpayable",
    },
];
var CounterScriptAbi__factory = /** @class */ (function () {
    function CounterScriptAbi__factory() {
    }
    CounterScriptAbi__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    CounterScriptAbi__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    CounterScriptAbi__factory.abi = _abi;
    return CounterScriptAbi__factory;
}());
exports.CounterScriptAbi__factory = CounterScriptAbi__factory;
