"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CounterScriptAbi__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var CounterScriptAbi__factory_1 = require("./CounterScriptAbi__factory");
Object.defineProperty(exports, "CounterScriptAbi__factory", { enumerable: true, get: function () { return CounterScriptAbi__factory_1.CounterScriptAbi__factory; } });
