"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ScriptAbi__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var ScriptAbi__factory_1 = require("./ScriptAbi__factory");
Object.defineProperty(exports, "ScriptAbi__factory", { enumerable: true, get: function () { return ScriptAbi__factory_1.ScriptAbi__factory; } });
