"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ScriptAbi__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        type: "function",
        name: "IS_SCRIPT",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "bool",
                internalType: "bool",
            },
        ],
        stateMutability: "view",
    },
];
var ScriptAbi__factory = /** @class */ (function () {
    function ScriptAbi__factory() {
    }
    ScriptAbi__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    ScriptAbi__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    ScriptAbi__factory.abi = _abi;
    return ScriptAbi__factory;
}());
exports.ScriptAbi__factory = ScriptAbi__factory;
