/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { ScriptAbi, ScriptAbiInterface } from "../../Script.sol/ScriptAbi";

const _abi = [
  {
    type: "function",
    name: "IS_SCRIPT",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
] as const;

export class ScriptAbi__factory {
  static readonly abi = _abi;
  static createInterface(): ScriptAbiInterface {
    return new utils.Interface(_abi) as ScriptAbiInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ScriptAbi {
    return new Contract(address, _abi, signerOrProvider) as ScriptAbi;
  }
}
