"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IMulticall3Abi__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var IMulticall3Abi__factory_1 = require("./IMulticall3Abi__factory");
Object.defineProperty(exports, "IMulticall3Abi__factory", { enumerable: true, get: function () { return IMulticall3Abi__factory_1.IMulticall3Abi__factory; } });
