"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TestAbi__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var TestAbi__factory_1 = require("./TestAbi__factory");
Object.defineProperty(exports, "TestAbi__factory", { enumerable: true, get: function () { return TestAbi__factory_1.TestAbi__factory; } });
