"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.VmSafeAbi__factory = exports.VmAbi__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var VmAbi__factory_1 = require("./VmAbi__factory");
Object.defineProperty(exports, "VmAbi__factory", { enumerable: true, get: function () { return VmAbi__factory_1.VmAbi__factory; } });
var VmSafeAbi__factory_1 = require("./VmSafeAbi__factory");
Object.defineProperty(exports, "VmSafeAbi__factory", { enumerable: true, get: function () { return VmSafeAbi__factory_1.VmSafeAbi__factory; } });
