"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MockERC20Abi__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var MockERC20Abi__factory_1 = require("./MockERC20Abi__factory");
Object.defineProperty(exports, "MockERC20Abi__factory", { enumerable: true, get: function () { return MockERC20Abi__factory_1.MockERC20Abi__factory; } });
