/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export type StateCommitmentStruct = {
  timestamp: PromiseOrValue<BigNumberish>;
  overlayRoot: PromiseOrValue<BytesLike>;
  stateRoot: PromiseOrValue<BytesLike>;
};

export type StateCommitmentStructOutput = [BigNumber, string, string] & {
  timestamp: BigNumber;
  overlayRoot: string;
  stateRoot: string;
};

export type IntermediateStateStruct = {
  stateMachineId: PromiseOrValue<BigNumberish>;
  height: PromiseOrValue<BigNumberish>;
  commitment: StateCommitmentStruct;
};

export type IntermediateStateStructOutput = [
  BigNumber,
  BigNumber,
  StateCommitmentStructOutput
] & {
  stateMachineId: BigNumber;
  height: BigNumber;
  commitment: StateCommitmentStructOutput;
};

export interface IConsensusClientAbiInterface extends utils.Interface {
  functions: {
    "verifyConsensus(bytes,bytes)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "verifyConsensus"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "verifyConsensus",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>]
  ): string;

  decodeFunctionResult(
    functionFragment: "verifyConsensus",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IConsensusClientAbi extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IConsensusClientAbiInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    verifyConsensus(
      trustedState: PromiseOrValue<BytesLike>,
      proof: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  verifyConsensus(
    trustedState: PromiseOrValue<BytesLike>,
    proof: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    verifyConsensus(
      trustedState: PromiseOrValue<BytesLike>,
      proof: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string, IntermediateStateStructOutput]>;
  };

  filters: {};

  estimateGas: {
    verifyConsensus(
      trustedState: PromiseOrValue<BytesLike>,
      proof: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    verifyConsensus(
      trustedState: PromiseOrValue<BytesLike>,
      proof: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
