"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.StdInvariantAbi__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var StdInvariantAbi__factory_1 = require("./StdInvariantAbi__factory");
Object.defineProperty(exports, "StdInvariantAbi__factory", { enumerable: true, get: function () { return StdInvariantAbi__factory_1.StdInvariantAbi__factory; } });
