/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { HypertentsAbi } from "./HypertentsAbi";
export type { ITokenFaucetAbi } from "./ITokenFaucetAbi";
