"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IConsensusClientAbi__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        type: "function",
        name: "verifyConsensus",
        inputs: [
            {
                name: "trustedState",
                type: "bytes",
                internalType: "bytes",
            },
            {
                name: "proof",
                type: "bytes",
                internalType: "bytes",
            },
        ],
        outputs: [
            {
                name: "",
                type: "bytes",
                internalType: "bytes",
            },
            {
                name: "",
                type: "tuple",
                internalType: "struct IntermediateState",
                components: [
                    {
                        name: "stateMachineId",
                        type: "uint256",
                        internalType: "uint256",
                    },
                    {
                        name: "height",
                        type: "uint256",
                        internalType: "uint256",
                    },
                    {
                        name: "commitment",
                        type: "tuple",
                        internalType: "struct StateCommitment",
                        components: [
                            {
                                name: "timestamp",
                                type: "uint256",
                                internalType: "uint256",
                            },
                            {
                                name: "overlayRoot",
                                type: "bytes32",
                                internalType: "bytes32",
                            },
                            {
                                name: "stateRoot",
                                type: "bytes32",
                                internalType: "bytes32",
                            },
                        ],
                    },
                ],
            },
        ],
        stateMutability: "nonpayable",
    },
];
var IConsensusClientAbi__factory = /** @class */ (function () {
    function IConsensusClientAbi__factory() {
    }
    IConsensusClientAbi__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    IConsensusClientAbi__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    IConsensusClientAbi__factory.abi = _abi;
    return IConsensusClientAbi__factory;
}());
exports.IConsensusClientAbi__factory = IConsensusClientAbi__factory;
