"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IConsensusClientAbi__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var IConsensusClientAbi__factory_1 = require("./IConsensusClientAbi__factory");
Object.defineProperty(exports, "IConsensusClientAbi__factory", { enumerable: true, get: function () { return IConsensusClientAbi__factory_1.IConsensusClientAbi__factory; } });
