"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.StdAssertionsAbi__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var StdAssertionsAbi__factory_1 = require("./StdAssertionsAbi__factory");
Object.defineProperty(exports, "StdAssertionsAbi__factory", { enumerable: true, get: function () { return StdAssertionsAbi__factory_1.StdAssertionsAbi__factory; } });
