"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.StdStorageSafeAbi__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var StdStorageSafeAbi__factory_1 = require("./StdStorageSafeAbi__factory");
Object.defineProperty(exports, "StdStorageSafeAbi__factory", { enumerable: true, get: function () { return StdStorageSafeAbi__factory_1.StdStorageSafeAbi__factory; } });
