"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BaseTestAbi__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var BaseTestAbi__factory_1 = require("./BaseTestAbi__factory");
Object.defineProperty(exports, "BaseTestAbi__factory", { enumerable: true, get: function () { return BaseTestAbi__factory_1.BaseTestAbi__factory; } });
