"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IERC165Abi__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var IERC165Abi__factory_1 = require("./IERC165Abi__factory");
Object.defineProperty(exports, "IERC165Abi__factory", { enumerable: true, get: function () { return IERC165Abi__factory_1.IERC165Abi__factory; } });
