"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MockERC721Abi__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var MockERC721Abi__factory_1 = require("./MockERC721Abi__factory");
Object.defineProperty(exports, "MockERC721Abi__factory", { enumerable: true, get: function () { return MockERC721Abi__factory_1.MockERC721Abi__factory; } });
