"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IIsmpModuleAbi__factory = exports.BaseIsmpModuleAbi__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var BaseIsmpModuleAbi__factory_1 = require("./BaseIsmpModuleAbi__factory");
Object.defineProperty(exports, "BaseIsmpModuleAbi__factory", { enumerable: true, get: function () { return BaseIsmpModuleAbi__factory_1.BaseIsmpModuleAbi__factory; } });
var IIsmpModuleAbi__factory_1 = require("./IIsmpModuleAbi__factory");
Object.defineProperty(exports, "IIsmpModuleAbi__factory", { enumerable: true, get: function () { return IIsmpModuleAbi__factory_1.IIsmpModuleAbi__factory; } });
