/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IIsmpHostAbi,
  IIsmpHostAbiInterface,
} from "../../IIsmpHost.sol/IIsmpHostAbi";

const _abi = [
  {
    type: "function",
    name: "admin",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "challengePeriod",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "consensusClient",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "consensusState",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "consensusUpdateTime",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "deleteStateMachineCommitment",
    inputs: [
      {
        name: "height",
        type: "tuple",
        internalType: "struct StateMachineHeight",
        components: [
          {
            name: "stateMachineId",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "height",
            type: "uint256",
            internalType: "uint256",
          },
        ],
      },
      {
        name: "fisherman",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "dispatch",
    inputs: [
      {
        name: "response",
        type: "tuple",
        internalType: "struct DispatchPostResponse",
        components: [
          {
            name: "request",
            type: "tuple",
            internalType: "struct PostRequest",
            components: [
              {
                name: "source",
                type: "bytes",
                internalType: "bytes",
              },
              {
                name: "dest",
                type: "bytes",
                internalType: "bytes",
              },
              {
                name: "nonce",
                type: "uint64",
                internalType: "uint64",
              },
              {
                name: "from",
                type: "bytes",
                internalType: "bytes",
              },
              {
                name: "to",
                type: "bytes",
                internalType: "bytes",
              },
              {
                name: "timeoutTimestamp",
                type: "uint64",
                internalType: "uint64",
              },
              {
                name: "body",
                type: "bytes",
                internalType: "bytes",
              },
            ],
          },
          {
            name: "response",
            type: "bytes",
            internalType: "bytes",
          },
          {
            name: "timeout",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "fee",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "payer",
            type: "address",
            internalType: "address",
          },
        ],
      },
    ],
    outputs: [
      {
        name: "commitment",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "dispatch",
    inputs: [
      {
        name: "request",
        type: "tuple",
        internalType: "struct DispatchPost",
        components: [
          {
            name: "dest",
            type: "bytes",
            internalType: "bytes",
          },
          {
            name: "to",
            type: "bytes",
            internalType: "bytes",
          },
          {
            name: "body",
            type: "bytes",
            internalType: "bytes",
          },
          {
            name: "timeout",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "fee",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "payer",
            type: "address",
            internalType: "address",
          },
        ],
      },
    ],
    outputs: [
      {
        name: "commitment",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "dispatch",
    inputs: [
      {
        name: "request",
        type: "tuple",
        internalType: "struct DispatchGet",
        components: [
          {
            name: "dest",
            type: "bytes",
            internalType: "bytes",
          },
          {
            name: "height",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "keys",
            type: "bytes[]",
            internalType: "bytes[]",
          },
          {
            name: "timeout",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "fee",
            type: "uint256",
            internalType: "uint256",
          },
        ],
      },
    ],
    outputs: [
      {
        name: "commitment",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "dispatchIncoming",
    inputs: [
      {
        name: "response",
        type: "tuple",
        internalType: "struct PostResponse",
        components: [
          {
            name: "request",
            type: "tuple",
            internalType: "struct PostRequest",
            components: [
              {
                name: "source",
                type: "bytes",
                internalType: "bytes",
              },
              {
                name: "dest",
                type: "bytes",
                internalType: "bytes",
              },
              {
                name: "nonce",
                type: "uint64",
                internalType: "uint64",
              },
              {
                name: "from",
                type: "bytes",
                internalType: "bytes",
              },
              {
                name: "to",
                type: "bytes",
                internalType: "bytes",
              },
              {
                name: "timeoutTimestamp",
                type: "uint64",
                internalType: "uint64",
              },
              {
                name: "body",
                type: "bytes",
                internalType: "bytes",
              },
            ],
          },
          {
            name: "response",
            type: "bytes",
            internalType: "bytes",
          },
          {
            name: "timeoutTimestamp",
            type: "uint64",
            internalType: "uint64",
          },
        ],
      },
      {
        name: "relayer",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "dispatchIncoming",
    inputs: [
      {
        name: "request",
        type: "tuple",
        internalType: "struct PostRequest",
        components: [
          {
            name: "source",
            type: "bytes",
            internalType: "bytes",
          },
          {
            name: "dest",
            type: "bytes",
            internalType: "bytes",
          },
          {
            name: "nonce",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "from",
            type: "bytes",
            internalType: "bytes",
          },
          {
            name: "to",
            type: "bytes",
            internalType: "bytes",
          },
          {
            name: "timeoutTimestamp",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "body",
            type: "bytes",
            internalType: "bytes",
          },
        ],
      },
      {
        name: "relayer",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "dispatchIncoming",
    inputs: [
      {
        name: "response",
        type: "tuple",
        internalType: "struct GetResponse",
        components: [
          {
            name: "request",
            type: "tuple",
            internalType: "struct GetRequest",
            components: [
              {
                name: "source",
                type: "bytes",
                internalType: "bytes",
              },
              {
                name: "dest",
                type: "bytes",
                internalType: "bytes",
              },
              {
                name: "nonce",
                type: "uint64",
                internalType: "uint64",
              },
              {
                name: "from",
                type: "address",
                internalType: "address",
              },
              {
                name: "timeoutTimestamp",
                type: "uint64",
                internalType: "uint64",
              },
              {
                name: "keys",
                type: "bytes[]",
                internalType: "bytes[]",
              },
              {
                name: "height",
                type: "uint64",
                internalType: "uint64",
              },
            ],
          },
          {
            name: "values",
            type: "tuple[]",
            internalType: "struct StorageValue[]",
            components: [
              {
                name: "key",
                type: "bytes",
                internalType: "bytes",
              },
              {
                name: "value",
                type: "bytes",
                internalType: "bytes",
              },
            ],
          },
        ],
      },
      {
        name: "relayer",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "dispatchTimeOut",
    inputs: [
      {
        name: "timeout",
        type: "tuple",
        internalType: "struct GetRequest",
        components: [
          {
            name: "source",
            type: "bytes",
            internalType: "bytes",
          },
          {
            name: "dest",
            type: "bytes",
            internalType: "bytes",
          },
          {
            name: "nonce",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "from",
            type: "address",
            internalType: "address",
          },
          {
            name: "timeoutTimestamp",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "keys",
            type: "bytes[]",
            internalType: "bytes[]",
          },
          {
            name: "height",
            type: "uint64",
            internalType: "uint64",
          },
        ],
      },
      {
        name: "meta",
        type: "tuple",
        internalType: "struct FeeMetadata",
        components: [
          {
            name: "fee",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "sender",
            type: "address",
            internalType: "address",
          },
        ],
      },
      {
        name: "commitment",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "dispatchTimeOut",
    inputs: [
      {
        name: "timeout",
        type: "tuple",
        internalType: "struct PostResponse",
        components: [
          {
            name: "request",
            type: "tuple",
            internalType: "struct PostRequest",
            components: [
              {
                name: "source",
                type: "bytes",
                internalType: "bytes",
              },
              {
                name: "dest",
                type: "bytes",
                internalType: "bytes",
              },
              {
                name: "nonce",
                type: "uint64",
                internalType: "uint64",
              },
              {
                name: "from",
                type: "bytes",
                internalType: "bytes",
              },
              {
                name: "to",
                type: "bytes",
                internalType: "bytes",
              },
              {
                name: "timeoutTimestamp",
                type: "uint64",
                internalType: "uint64",
              },
              {
                name: "body",
                type: "bytes",
                internalType: "bytes",
              },
            ],
          },
          {
            name: "response",
            type: "bytes",
            internalType: "bytes",
          },
          {
            name: "timeoutTimestamp",
            type: "uint64",
            internalType: "uint64",
          },
        ],
      },
      {
        name: "meta",
        type: "tuple",
        internalType: "struct FeeMetadata",
        components: [
          {
            name: "fee",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "sender",
            type: "address",
            internalType: "address",
          },
        ],
      },
      {
        name: "commitment",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "dispatchTimeOut",
    inputs: [
      {
        name: "timeout",
        type: "tuple",
        internalType: "struct PostRequest",
        components: [
          {
            name: "source",
            type: "bytes",
            internalType: "bytes",
          },
          {
            name: "dest",
            type: "bytes",
            internalType: "bytes",
          },
          {
            name: "nonce",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "from",
            type: "bytes",
            internalType: "bytes",
          },
          {
            name: "to",
            type: "bytes",
            internalType: "bytes",
          },
          {
            name: "timeoutTimestamp",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "body",
            type: "bytes",
            internalType: "bytes",
          },
        ],
      },
      {
        name: "meta",
        type: "tuple",
        internalType: "struct FeeMetadata",
        components: [
          {
            name: "fee",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "sender",
            type: "address",
            internalType: "address",
          },
        ],
      },
      {
        name: "commitment",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "feeToken",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "frozen",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint8",
        internalType: "enum FrozenStatus",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "fundRequest",
    inputs: [
      {
        name: "commitment",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "amount",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "fundResponse",
    inputs: [
      {
        name: "commitment",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "amount",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "host",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hyperbridge",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "latestStateMachineHeight",
    inputs: [
      {
        name: "stateMachineId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "nonce",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "perByteFee",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "requestCommitments",
    inputs: [
      {
        name: "commitment",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct FeeMetadata",
        components: [
          {
            name: "fee",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "sender",
            type: "address",
            internalType: "address",
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "requestReceipts",
    inputs: [
      {
        name: "commitment",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "responded",
    inputs: [
      {
        name: "commitment",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [
      {
        name: "",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "responseCommitments",
    inputs: [
      {
        name: "commitment",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct FeeMetadata",
        components: [
          {
            name: "fee",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "sender",
            type: "address",
            internalType: "address",
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "responseReceipts",
    inputs: [
      {
        name: "commitment",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct ResponseReceipt",
        components: [
          {
            name: "responseCommitment",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "relayer",
            type: "address",
            internalType: "address",
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "setFrozenState",
    inputs: [
      {
        name: "newState",
        type: "uint8",
        internalType: "enum FrozenStatus",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "stateCommitmentFee",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "stateMachineCommitment",
    inputs: [
      {
        name: "height",
        type: "tuple",
        internalType: "struct StateMachineHeight",
        components: [
          {
            name: "stateMachineId",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "height",
            type: "uint256",
            internalType: "uint256",
          },
        ],
      },
    ],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct StateCommitment",
        components: [
          {
            name: "timestamp",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "overlayRoot",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "stateRoot",
            type: "bytes32",
            internalType: "bytes32",
          },
        ],
      },
    ],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "stateMachineCommitmentUpdateTime",
    inputs: [
      {
        name: "height",
        type: "tuple",
        internalType: "struct StateMachineHeight",
        components: [
          {
            name: "stateMachineId",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "height",
            type: "uint256",
            internalType: "uint256",
          },
        ],
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "storeConsensusState",
    inputs: [
      {
        name: "state",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "storeStateMachineCommitment",
    inputs: [
      {
        name: "height",
        type: "tuple",
        internalType: "struct StateMachineHeight",
        components: [
          {
            name: "stateMachineId",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "height",
            type: "uint256",
            internalType: "uint256",
          },
        ],
      },
      {
        name: "commitment",
        type: "tuple",
        internalType: "struct StateCommitment",
        components: [
          {
            name: "timestamp",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "overlayRoot",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "stateRoot",
            type: "bytes32",
            internalType: "bytes32",
          },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "timestamp",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "unStakingPeriod",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "uniswapV2Router",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "vetoes",
    inputs: [
      {
        name: "paraId",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "height",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
] as const;

export class IIsmpHostAbi__factory {
  static readonly abi = _abi;
  static createInterface(): IIsmpHostAbiInterface {
    return new utils.Interface(_abi) as IIsmpHostAbiInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IIsmpHostAbi {
    return new Contract(address, _abi, signerOrProvider) as IIsmpHostAbi;
  }
}
