"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IIsmpHostAbi__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var IIsmpHostAbi__factory_1 = require("./IIsmpHostAbi__factory");
Object.defineProperty(exports, "IIsmpHostAbi__factory", { enumerable: true, get: function () { return IIsmpHostAbi__factory_1.IIsmpHostAbi__factory; } });
