"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IERC20PermitAbi__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var IERC20PermitAbi__factory_1 = require("./IERC20PermitAbi__factory");
Object.defineProperty(exports, "IERC20PermitAbi__factory", { enumerable: true, get: function () { return IERC20PermitAbi__factory_1.IERC20PermitAbi__factory; } });
