/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BaseIsmpModuleAbi } from "./BaseIsmpModuleAbi";
export type { IIsmpModuleAbi } from "./IIsmpModuleAbi";
