"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ISettlementContractAbi__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var ISettlementContractAbi__factory_1 = require("./ISettlementContractAbi__factory");
Object.defineProperty(exports, "ISettlementContractAbi__factory", { enumerable: true, get: function () { return ISettlementContractAbi__factory_1.ISettlementContractAbi__factory; } });
