/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ISettlementContractAbi,
  ISettlementContractAbiInterface,
} from "../../ERC7683.sol/ISettlementContractAbi";

const _abi = [
  {
    type: "function",
    name: "initiate",
    inputs: [
      {
        name: "order",
        type: "tuple",
        internalType: "struct CrossChainOrder",
        components: [
          {
            name: "settlementContract",
            type: "address",
            internalType: "address",
          },
          {
            name: "swapper",
            type: "address",
            internalType: "address",
          },
          {
            name: "nonce",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "originChainId",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "initiateDeadline",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "fillDeadline",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "orderData",
            type: "bytes",
            internalType: "bytes",
          },
        ],
      },
      {
        name: "signature",
        type: "bytes",
        internalType: "bytes",
      },
      {
        name: "fillerData",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "resolve",
    inputs: [
      {
        name: "order",
        type: "tuple",
        internalType: "struct CrossChainOrder",
        components: [
          {
            name: "settlementContract",
            type: "address",
            internalType: "address",
          },
          {
            name: "swapper",
            type: "address",
            internalType: "address",
          },
          {
            name: "nonce",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "originChainId",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "initiateDeadline",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "fillDeadline",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "orderData",
            type: "bytes",
            internalType: "bytes",
          },
        ],
      },
      {
        name: "fillerData",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct ResolvedCrossChainOrder",
        components: [
          {
            name: "settlementContract",
            type: "address",
            internalType: "address",
          },
          {
            name: "swapper",
            type: "address",
            internalType: "address",
          },
          {
            name: "nonce",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "originChainId",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "initiateDeadline",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "fillDeadline",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "swapperInputs",
            type: "tuple[]",
            internalType: "struct Input[]",
            components: [
              {
                name: "token",
                type: "address",
                internalType: "address",
              },
              {
                name: "amount",
                type: "uint256",
                internalType: "uint256",
              },
            ],
          },
          {
            name: "swapperOutputs",
            type: "tuple[]",
            internalType: "struct Output[]",
            components: [
              {
                name: "token",
                type: "address",
                internalType: "address",
              },
              {
                name: "amount",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "recipient",
                type: "address",
                internalType: "address",
              },
              {
                name: "chainId",
                type: "uint32",
                internalType: "uint32",
              },
            ],
          },
          {
            name: "fillerOutputs",
            type: "tuple[]",
            internalType: "struct Output[]",
            components: [
              {
                name: "token",
                type: "address",
                internalType: "address",
              },
              {
                name: "amount",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "recipient",
                type: "address",
                internalType: "address",
              },
              {
                name: "chainId",
                type: "uint32",
                internalType: "uint32",
              },
            ],
          },
        ],
      },
    ],
    stateMutability: "view",
  },
] as const;

export class ISettlementContractAbi__factory {
  static readonly abi = _abi;
  static createInterface(): ISettlementContractAbiInterface {
    return new utils.Interface(_abi) as ISettlementContractAbiInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISettlementContractAbi {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ISettlementContractAbi;
  }
}
