"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ISettlementContractAbi__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        type: "function",
        name: "initiate",
        inputs: [
            {
                name: "order",
                type: "tuple",
                internalType: "struct CrossChainOrder",
                components: [
                    {
                        name: "settlementContract",
                        type: "address",
                        internalType: "address",
                    },
                    {
                        name: "swapper",
                        type: "address",
                        internalType: "address",
                    },
                    {
                        name: "nonce",
                        type: "uint256",
                        internalType: "uint256",
                    },
                    {
                        name: "originChainId",
                        type: "uint32",
                        internalType: "uint32",
                    },
                    {
                        name: "initiateDeadline",
                        type: "uint32",
                        internalType: "uint32",
                    },
                    {
                        name: "fillDeadline",
                        type: "uint32",
                        internalType: "uint32",
                    },
                    {
                        name: "orderData",
                        type: "bytes",
                        internalType: "bytes",
                    },
                ],
            },
            {
                name: "signature",
                type: "bytes",
                internalType: "bytes",
            },
            {
                name: "fillerData",
                type: "bytes",
                internalType: "bytes",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "resolve",
        inputs: [
            {
                name: "order",
                type: "tuple",
                internalType: "struct CrossChainOrder",
                components: [
                    {
                        name: "settlementContract",
                        type: "address",
                        internalType: "address",
                    },
                    {
                        name: "swapper",
                        type: "address",
                        internalType: "address",
                    },
                    {
                        name: "nonce",
                        type: "uint256",
                        internalType: "uint256",
                    },
                    {
                        name: "originChainId",
                        type: "uint32",
                        internalType: "uint32",
                    },
                    {
                        name: "initiateDeadline",
                        type: "uint32",
                        internalType: "uint32",
                    },
                    {
                        name: "fillDeadline",
                        type: "uint32",
                        internalType: "uint32",
                    },
                    {
                        name: "orderData",
                        type: "bytes",
                        internalType: "bytes",
                    },
                ],
            },
            {
                name: "fillerData",
                type: "bytes",
                internalType: "bytes",
            },
        ],
        outputs: [
            {
                name: "",
                type: "tuple",
                internalType: "struct ResolvedCrossChainOrder",
                components: [
                    {
                        name: "settlementContract",
                        type: "address",
                        internalType: "address",
                    },
                    {
                        name: "swapper",
                        type: "address",
                        internalType: "address",
                    },
                    {
                        name: "nonce",
                        type: "uint256",
                        internalType: "uint256",
                    },
                    {
                        name: "originChainId",
                        type: "uint32",
                        internalType: "uint32",
                    },
                    {
                        name: "initiateDeadline",
                        type: "uint32",
                        internalType: "uint32",
                    },
                    {
                        name: "fillDeadline",
                        type: "uint32",
                        internalType: "uint32",
                    },
                    {
                        name: "swapperInputs",
                        type: "tuple[]",
                        internalType: "struct Input[]",
                        components: [
                            {
                                name: "token",
                                type: "address",
                                internalType: "address",
                            },
                            {
                                name: "amount",
                                type: "uint256",
                                internalType: "uint256",
                            },
                        ],
                    },
                    {
                        name: "swapperOutputs",
                        type: "tuple[]",
                        internalType: "struct Output[]",
                        components: [
                            {
                                name: "token",
                                type: "address",
                                internalType: "address",
                            },
                            {
                                name: "amount",
                                type: "uint256",
                                internalType: "uint256",
                            },
                            {
                                name: "recipient",
                                type: "address",
                                internalType: "address",
                            },
                            {
                                name: "chainId",
                                type: "uint32",
                                internalType: "uint32",
                            },
                        ],
                    },
                    {
                        name: "fillerOutputs",
                        type: "tuple[]",
                        internalType: "struct Output[]",
                        components: [
                            {
                                name: "token",
                                type: "address",
                                internalType: "address",
                            },
                            {
                                name: "amount",
                                type: "uint256",
                                internalType: "uint256",
                            },
                            {
                                name: "recipient",
                                type: "address",
                                internalType: "address",
                            },
                            {
                                name: "chainId",
                                type: "uint32",
                                internalType: "uint32",
                            },
                        ],
                    },
                ],
            },
        ],
        stateMutability: "view",
    },
];
var ISettlementContractAbi__factory = /** @class */ (function () {
    function ISettlementContractAbi__factory() {
    }
    ISettlementContractAbi__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    ISettlementContractAbi__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    ISettlementContractAbi__factory.abi = _abi;
    return ISettlementContractAbi__factory;
}());
exports.ISettlementContractAbi__factory = ISettlementContractAbi__factory;
