"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ITokenFaucetAbi__factory = exports.HypertentsAbi__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var HypertentsAbi__factory_1 = require("./HypertentsAbi__factory");
Object.defineProperty(exports, "HypertentsAbi__factory", { enumerable: true, get: function () { return HypertentsAbi__factory_1.HypertentsAbi__factory; } });
var ITokenFaucetAbi__factory_1 = require("./ITokenFaucetAbi__factory");
Object.defineProperty(exports, "ITokenFaucetAbi__factory", { enumerable: true, get: function () { return ITokenFaucetAbi__factory_1.ITokenFaucetAbi__factory; } });
