"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ITokenFaucetAbi__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        type: "function",
        name: "drip",
        inputs: [
            {
                name: "",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
];
var ITokenFaucetAbi__factory = /** @class */ (function () {
    function ITokenFaucetAbi__factory() {
    }
    ITokenFaucetAbi__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    ITokenFaucetAbi__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    ITokenFaucetAbi__factory.abi = _abi;
    return ITokenFaucetAbi__factory;
}());
exports.ITokenFaucetAbi__factory = ITokenFaucetAbi__factory;
