/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ITokenFaucetAbi,
  ITokenFaucetAbiInterface,
} from "../../Hypertents.sol/ITokenFaucetAbi";

const _abi = [
  {
    type: "function",
    name: "drip",
    inputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
] as const;

export class ITokenFaucetAbi__factory {
  static readonly abi = _abi;
  static createInterface(): ITokenFaucetAbiInterface {
    return new utils.Interface(_abi) as ITokenFaucetAbiInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITokenFaucetAbi {
    return new Contract(address, _abi, signerOrProvider) as ITokenFaucetAbi;
  }
}
