"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IERC20Abi__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var IERC20Abi__factory_1 = require("./IERC20Abi__factory");
Object.defineProperty(exports, "IERC20Abi__factory", { enumerable: true, get: function () { return IERC20Abi__factory_1.IERC20Abi__factory; } });
