"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IERC721TokenReceiverAbi__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        type: "function",
        name: "onERC721Received",
        inputs: [
            {
                name: "_operator",
                type: "address",
                internalType: "address",
            },
            {
                name: "_from",
                type: "address",
                internalType: "address",
            },
            {
                name: "_tokenId",
                type: "uint256",
                internalType: "uint256",
            },
            {
                name: "_data",
                type: "bytes",
                internalType: "bytes",
            },
        ],
        outputs: [
            {
                name: "",
                type: "bytes4",
                internalType: "bytes4",
            },
        ],
        stateMutability: "nonpayable",
    },
];
var IERC721TokenReceiverAbi__factory = /** @class */ (function () {
    function IERC721TokenReceiverAbi__factory() {
    }
    IERC721TokenReceiverAbi__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    IERC721TokenReceiverAbi__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    IERC721TokenReceiverAbi__factory.abi = _abi;
    return IERC721TokenReceiverAbi__factory;
}());
exports.IERC721TokenReceiverAbi__factory = IERC721TokenReceiverAbi__factory;
