/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IERC721TokenReceiverAbi,
  IERC721TokenReceiverAbiInterface,
} from "../../IERC721.sol/IERC721TokenReceiverAbi";

const _abi = [
  {
    type: "function",
    name: "onERC721Received",
    inputs: [
      {
        name: "_operator",
        type: "address",
        internalType: "address",
      },
      {
        name: "_from",
        type: "address",
        internalType: "address",
      },
      {
        name: "_tokenId",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "_data",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    outputs: [
      {
        name: "",
        type: "bytes4",
        internalType: "bytes4",
      },
    ],
    stateMutability: "nonpayable",
  },
] as const;

export class IERC721TokenReceiverAbi__factory {
  static readonly abi = _abi;
  static createInterface(): IERC721TokenReceiverAbiInterface {
    return new utils.Interface(_abi) as IERC721TokenReceiverAbiInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC721TokenReceiverAbi {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IERC721TokenReceiverAbi;
  }
}
