"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.StdErrorAbi__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var StdErrorAbi__factory_1 = require("./StdErrorAbi__factory");
Object.defineProperty(exports, "StdErrorAbi__factory", { enumerable: true, get: function () { return StdErrorAbi__factory_1.StdErrorAbi__factory; } });
