"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IDispatcherAbi__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var IDispatcherAbi__factory_1 = require("./IDispatcherAbi__factory");
Object.defineProperty(exports, "IDispatcherAbi__factory", { enumerable: true, get: function () { return IDispatcherAbi__factory_1.IDispatcherAbi__factory; } });
